BN:
  NUM_SAMPLES_PRECISE: 1024
  USE_PRECISE_STATS: true
CUDNN:
  BENCHMARK: false
DATA_LOADER:
  NUM_WORKERS: 4
MODEL:
  DEPTH: 12
#  EMBED_DIM: 256
#  MLP_DIM: 512
  NUM_CLASSES: 10
#  NUM_HEADS: 8
#  PATCH_SIZE: 4
  TYPE: vitnet
NUM_GPUS: 1
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: true
  WEIGHT_DECAY: 0.0005
OUT_DIR: .
RESNET:
  TRANS_FUN: vit
RGRAPH:
  DIM_FIRST: 512
  DIM_LIST:
  - 512
  GROUP_NUM: 256
#  MESSAGE_TYPE: 8
  P: 100.0
  SPARSITY: 12.0
  TALK_MODE: dense
TEST:
  BATCH_SIZE: 100
  DATASET: cifar10
  SPLIT: test
TRAIN:
  BATCH_SIZE: 128
  CHECKPOINT_PERIOD: 500
  DATASET: cifar10
  EVAL_PERIOD: 1
  SPLIT: train
